# Generated by Django 5.2 on 2025-06-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=255)),
                ('st_surname', models.CharField(max_length=255)),
                ('st_group', models.CharField(max_length=255, null=True)),
                ('st_course', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='univer.teacher')),
            ],
        ),
    ]
